### PR TITLE
Add an util to read application credentials from a config file.

### PR DESCRIPTION
**Pull request by jingw222**
Hi, 

Just added a convenient utility function to read application credentials from a file. For example:

```
# config.ini
[DEFAULT]
SPOTIPY_CLIENT_ID = abcdefgh
SPOTIPY_CLIENT_SECRET = 0123456789
SPOTIPY_REDIRECT_URI = http://localhost:5000/login_callback
```
and then read the file simply by:
```
from spotipy import util
util.credentials_from_configfile(file_path='config.ini', section='DEFAULT')
```
Also we can easily add and switch between multiple developer applications by adding them under different sections.

### CODE REVIEW

**Comment by marioortizmanero** [comment]
How about being able to save the refresh token in the config file too for the future? I use something similar in my app already and it could come in handy in your implementation :)

**Comment by felix-hilden** [comment]
Hi! Thanks for the contribution, I like your idea 👍 Along with using environment variables, it should be the other main way of providing configuration. I'm a little bit hesitant on implementing too many utilities for specific uses, but I'm not sure where to draw the line.

This would need some simple tests, a temporary config could actually be written during those. Then some documentation, at least in the `util` top docstring, maybe in the guide documents as well. But let's discuss a bit first.

Some notes about the code:
- How about naming it `credentials_from_file` instead? The format would be implied.
- Aren't configparser's sections already dictionaries? Why the cast?

Other notes in no special order:
- The util module is starting to grow, maybe it should be broken down to different files. Perhaps one for config things, another for refreshing tokens. Then all public things could be imported to the top level of `util`.
- I'm starting to wonder whether the `SPOTIPY_CLIENT_ID` and such should be parameterisable. Now there are two places where they are used. We could either get rid of them completely and just assume the values, or maybe provide a way of setting them globally, like `spotipy.util.var.client_id = 'foobar'`. Not sure about this either.
- For some reason my gut reaction was to dislike the idea of providing a way of writing refresh tokens to the file. That would call for a way of writing the whole configfile, and providing a way of reading the refresh token. By extension, similar functions should then be implemented for environment variables as well. As I said above, I'm not sure where we should draw the line of implementing things for our users.

And if we start implementing many ways of reading and writing configuration, they could be classes or submodules in themselves. Like `util.config.env.read_credentials / read_refresh_token` or whatever, or maybe `util.config.EnvCredentials` with methods. Ideas?

**Comment by felix-hilden** [comment]
I added some tests and documentation, but it seems my rebase went wrong. I'll try to include only the relevant commits in this pull request.

**Comment by felix-hilden** [comment]
Nice, now we are back on track and your dev is on top of my latest commit. And by the way, thanks for enabling me to push to your branch. It makes things a lot easier. Here's my plan for the current PR now that the feature is in an acceptable state:
- Break `util` down to two files, one for token stuff, the other for reading configuration
- Disambiguate credentials, so use `Credentials` for tokens and `configuration` or `config` for application "credentials". This would mean renaming things to `config_from_environment`, `config_from_file` etc.
- Combine the two functions for reading dictionaries (config and environment)

Then, after this PR, let's open up an issue to add the ability to read user refresh token from environment or configfile. That could include removing the varname keyword arguments and making them assignable variables in the module for easier manipulation. After that we could consider writing configuration too.

**Comment by jingw222** [comment]
Nicely done! I'm pretty positive about the decisions you've made lately, including refactoring `util`, and cool neat stuff added there, as well as the intention to conceptually draw a line between `config` and `credentials`. But as I read the source, it seems just a little bit confusing in that:

1. By ambiguous credentials, did you mean `app_token` vs `user_token`? I think `config` and `credentials` in `util` basically complete two steps of setting up a `app_token`/`user_token`. In other words we first read credential variables from wherever they are, using `config`, and the next logical step is to feed them into a `Credential`constructor and send request, using `credentials`. 

2. `RefreshingToken` and `RefreshingCredentials` would be probably more fitting into `auth` module considering `Token` and `Credentials`. And since they're similar in functionality there could possibly be refactoring between them as well (Saw duplicated methods but have yet to try it myself). After that we can import the two classes from there, leaving `util` just small util functions. ;)

3. Lastly, this might be trivial, but I'm currently not be able to use the util functions directly from `util` by

    ```
    import spotipy
    conf = spotipy.util.config_from_environment()
    ```

    and I have to do `from spotipy import util` first instead, which makes some variables somewhat conflicting if you import other utility module from other packages. It would be a plus to have that option.

Happy new year and thanks for you great contribution to this project. Hope we'll see it on pypi soon.

**Comment by felix-hilden** [comment]
@jingw222 The ambiguousness was in e.g. `credentials_from_environment` and `RefreshingCredentials`. They are both named credentials, but one retrieves tokens, the other is used in application configuration. This was the concept that I wanted to separate. Configuration can also be thought of as application credentials, but the term was already reserved for tokens. You are right that `config -> credentials` is the way to go.

There's a reason I want to keep `RefreshingCredentials` in `util` and not `auth`. I want to keep a clear distinction between what's vanilla and what's extra. Automatically refreshing tokens are extra - logic that has been added on top of Spotify's API, and that some applications don't want. `RefreshingCredentials` started out as functions, but it was clear that building a class to mirror `auth` was the cleanest internal structure to go with. After all, why not provide it for the users - just for the sake of convenience. There are certainly duplicate methods, but as documented `RefreshingCredentials` delegates to `Credentials`. There is no functionality to refactor.

You are not able to use imports like that? Wow.. Thanks for the info, let's open up an issue right away.

You're most welcome :D Hope so too!

**Comment by jingw222** [comment]
> I want to keep a clear distinction between what's vanilla and what's extra. 

If that is the design philosophy I can totally get it and it does makes sense. But why not include for example `convert` under `util`, which is not necessarily a model object of Spotify API and certainly qualifies as some solid helper functions for the developers.

Oh, as for the importing issue, this is the same case for `scope`. In fact you can confirm that with a `dir(spotipy)`.

**Comment by felix-hilden** [comment]
I think a more solid analogue for `convert` would be if we implemented a function for guessing what a user has provided based on trying each of the conversion functions. That would be extra. Conversions, though extra in the sense that they are not directly related to API calls are very much a core part of the functionality.

But breaking `util` down to more descriptively named modules has crossed my mind. It's not that I'm totally against it. Let's see if the idea can be developed.

**Comment by jingw222** [comment]
Yay, that's legit. 

On `RefreshingCredentials`, can we incorporate the option to auto refresh a token as a init parameter for `Credentials`, like `auto_refresh=False`. It will not auto renew it by default. Maintaining two sets of mostly similar code under different parts of the package makes me a little edgy. 🤣😅

But of course it's ultimately up to you to draw a bigger picture and make it easier to use and sensible as a whole.

**Comment by felix-hilden** [comment]
That could actually be a solution! But there's a problem with the refreshing in that case. If `auto_refresh=False` we're all good. It's the old `Credentials`. Now if `auto_refresh=True`, a refreshing token is returned after checking the condition. So far so good. Internally the refreshing token has a plain `Token` which it reads to mimic the attributes and a `Credentilals` to refresh itself. When it comes time to refresh, the wrapped, plain token is refreshed. As a result the refreshing token wraps another refreshing token. This problem could be solved by examining the type of token that was returned and if it's the refreshing type, use its `_token` attribute.

I dislike the idea of adding a bunch of ifs to the code to change what's being returned. And `Credentials.refresh` doesn't make sense for refreshing credentials. Ideally `RefreshingCredentials` would have been a subclass of `Credentials`, but as I laid out above it doesn't quite fit in practice although conceptually it would. Would you agree?

**Pull request merged**
